---
title: ''
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load required packages
library(tidyverse)
library(DBI)
library(dbplyr)
library(keyring)
library(vroom)
library(rJava)
library(mailR)

#Store file path to faxing home directory, include trailing slash
#key_set("sti-fax-dir")
fax_dir <- key_get("sti-fax-dir")

#store sti staff emails for follow up
#key_set("sti_followup_emails")

#store sti programmer emails for control flow alerts 
#key_set("sti_programmer_emails")


```

```{r pull_providers}

#Note:Provider info kept in Microsoft Access database

#set pieces of database connection and construct string
db_path <- paste0(fax_dir, "_ProviderContactDatabaseForMissingSurveillanceInfo.accdb")
dbq_string <- paste0("DBQ=", db_path)
driver_string <- "Driver={Microsoft Access Driver (*.mdb, *.accdb)};"
db_connect_string <- paste0(driver_string, dbq_string)

#connect to provider info database
db_connection <- dbConnect(odbc::odbc(), .connection_string = db_connect_string)

#connect to database table with provider info and pull into R
providers <- tbl(db_connection, "OrgListCurrentSTD") %>%
  select(`Organization Name`:County) %>%
  collect() %>%
  janitor::clean_names() %>%
  mutate(across(where(is.character), ~na_if(.,""))) %>%
  mutate(across(where(is.character), toupper))

#close database connection
dbDisconnect(db_connection)

```

```{r import_exceptions}

#import exception files dated in the last week
all_files <- list.files(path = 'sti-exceptions', pattern = ".*csv", full.names = T)

files_this_week <- cbind(file = files,
              date = map_chr(files, ~str_extract(., "\\d{4}-\\d{2}-\\d{2}"))) %>%
  as.data.frame() %>%
  mutate(date = as.Date(date)) %>%
  filter(date > Sys.Date() - 7) %>%
  pull(file)

exceptions <- vroom(files_this_week) %>%
  distinct() 

```

```{r match_providers}

#match exceptions to provider information on organization name and city
exception_plus_provider <- exceptions %>%
  mutate(across(contains("Ordering"), toupper)) %>%
  separate(DiagnosisOrderingFacility, into = c("diagnosis_ordering_facility", "diagnosis_ordering_city", "diagnosis_ordering_phone"), sep = "; ") %>%
  mutate(matching_provider = ifelse(is.na(diagnosis_ordering_facility), OrderingFacilityName, diagnosis_ordering_facility),
         diagnosis_ordering_city = str_remove(diagnosis_ordering_city, ", .*"),
         diagnosis_ordering_phone = str_remove(diagnosis_ordering_phone, " "),
         ordering_city = case_when(
           grepl(", [A-Z]{2} ", OrderingFacilityAddress) ~ sub("(^.*, )(.*)(, [A-Z]{2}.*$)", "\\2", OrderingFacilityAddress),
           grepl("ACHN", OrderingFacilityAddress) ~ gsub("ACHN - | CLINIC.*$| HEALTH.*$| AMBULATORY.*$", "",OrderingFacilityAddress)),
         inedss_provider_city = trimws(ifelse(is.na(diagnosis_ordering_city), ordering_city, diagnosis_ordering_city))) %>%
  left_join(providers, by = c("matching_provider" = "organization_name", "inedss_provider_city" = "city")) 

#split dataset into those ready for faxing and those needing follow-up

#ready for faxing
matched_fax <- filter(exception_plus_provider, !is.na(fax))

#needs follow-up
no_fax <- filter(exception_plus_provider, is.na(fax) & !is.na(address_line_1))  #exists in provider DB but missing fax
no_provider_record <- filter(exception_plus_provider, is.na(fax) & is.na(address_line_1)) #doesn't exist in provider DB


```

```{r need_fax}

#format file for providers who are in DB but missing fax
no_fax_clean <- no_fax %>%
  select(matching_provider, address_line_1:county) %>%
  distinct() %>%
  rename(organization_name = matching_provider) %>%
  arrange(organization_name) %>%
  janitor::clean_names(case = "title")

#write file for follow up
write_csv(no_fax_clean, file = paste0(fax_dir, "Provider Follow Up/", Sys.Date(), "_providers-with-missing-fax.csv"))

#format file for providers who are not in DB
no_provider_record_clean <- no_provider_record %>%
  select(contains("ordering"), matching_provider) %>%
  distinct() %>%
  mutate(organization_name = matching_provider,
         diagnosis_ordering_facility = ifelse(is.na(diagnosis_ordering_facility), "UNKNOWN", diagnosis_ordering_facility),
         provider = ifelse(matching_provider == diagnosis_ordering_facility, DiagnosisOrderingProvider, OrderingProviderName),
         address = ifelse(matching_provider == diagnosis_ordering_facility, diagnosis_ordering_city, OrderingFacilityAddress),
         phone_1 = ifelse(matching_provider == diagnosis_ordering_facility, diagnosis_ordering_phone, OrderingFacilityPhone),
         phone_2 = ifelse(matching_provider == diagnosis_ordering_facility, OrderingFacilityPhone, OrderingProviderPhone),
         phone_3 = ifelse(matching_provider == diagnosis_ordering_facility, OrderingProviderPhone, NA)) %>%
  select(organization_name, provider:phone_3) %>%
  drop_na(organization_name) %>%
  group_by(organization_name) %>%
  mutate(provider_list = paste(provider, collapse = "; ")) %>%
  ungroup() %>%
  select(organization_name, provider_list, address:phone_3) %>%
  arrange(organization_name) %>%
  distinct() %>%
  janitor::clean_names(case = "title")

#write files for follow up
write_csv(no_provider_record_clean, file = paste0(fax_dir, "Provider Follow Up/", Sys.Date(), "_providers-with-no-database-record.csv"))

#send email to alert STI staff lists are ready for follow up
if(file.exists(paste0(fax_dir, "Provider Follow Up/", Sys.Date(), "_providers-with-no-database-record.csv"))){

  send.mail(from = key_get("cch_auto_email"),
            to = key_get("sti_followup_emails"),
            cc = key_get("sti_programmer_emails"),
            subject = "Biweekly Provider Follow Up Lists Are Ready",
            body = paste0("Provider lists requiring follow-up are ready in the STI folder: ", key_get("sti_provider_followup_folder")),
            html = TRUE,
            smtp = list(host.name = key_get("smtp_host"), 
                        user.name = key_get("smtp_user"),
                        passwd = key_get("Office365"), tls = TRUE),
            authenticate = TRUE,
            send = TRUE) 
  
}

```

 
```{r has_fax}

#Import current fax history
fax_history <- read_csv("fax-history.csv", col_types = c("cci"))

#Create list of maxed out faxes
maxed_out <- fax_history %>% filter(fax_counter >= 3) %>% pull(state_case_number)

#Remove cases that have already exceeded max number of faxes, clean provider name and clarify exceptions for provider audience
matched_fax_clean <- matched_fax %>%
  filter(!StateCaseNumber %in% maxed_out) %>%
  mutate(diagnosis_provider_clean = sub(";.*", "", DiagnosisOrderingProvider),
         provider_clean = str_to_title(ifelse(is.na(diagnosis_provider_clean), OrderingProviderName, diagnosis_provider_clean))) %>%
  mutate(Reason = gsub("County must be specified. State is required. The patient's address must be validated before the case can be closed.|City is required for Illinois address, 'unknown' will be acceptable.|If State is not 'Illinois', County must be 'Out of State'. ", "Address is missing or invalid.", Reason),
         Reason = gsub("is required.|is blank.|is entered as Unknown.|must be specified.", "is missing.", Reason),
         Reason = gsub("If start date is not blank, an adequate treatment is required.", "Treatment is missing.", Reason)) %>%
  filter(!grepl("case already exists for this person. Please work on a single case", Reason))
  
#Split list by provider for looping
matched_fax_list <- split(matched_fax_clean, matched_fax_clean$matching_provider)

#Create directory to save faxes
dir.create(paste0(fax_dir,"Faxes/", Sys.Date()))

#Loop through list and write fax cover sheets
for (i in 1:length(matched_fax_list)) {
  
  provider_data <- list(matched_fax_list[[i]])
  provider_name <- names(matched_fax_list)[i]
  rmarkdown::render(input = "provider-fax-template.Rmd",
                    output_file = paste0(fax_dir,"Faxes/", Sys.Date(), "/", provider_name),
                    params = list(data = provider_data))
  
}

#For cases being faxed for the first time, add to fax history
new_cases <- matched_fax_clean %>%
  filter(!StateCaseNumber %in% fax_history$state_case_number) %>%
  select(state_case_number = StateCaseNumber, event_date = EventDate) %>%
  mutate(fax_counter = 0)  #counter will iterate to 1 below

fax_history <- bind_rows(fax_history, new_cases)

#Increment fax counter for cases sent
fax_history <- fax_history %>% 
  mutate(fax_counter = ifelse(state_case_number %in% matched_fax_clean$StateCaseNumber, fax_counter + 1, fax_counter))

#Re-save fax history
write_csv(fax_history, "fax-history.csv")


```
 

 
 
